name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*'
      - 'config.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.GP_DEPLOY_KEY }}
    - uses: fregante/setup-git-user@v1
    - run: git remote add gh-pages ${{ secrets.GP_DEPLOY_REPO }}
    - uses: actions/setup-node@v3
      with:
         node-version: 18
         cache: 'npm'
         cache-dependency-path: '**/package-lock.json'
    - run: |
        npm ci
        npm run deploy
